# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyPay' do
  pod 'Stripe', '~> 14.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for EasyPay
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
  
  pod 'Braintree', '~> 4.19.0'
  
  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  target 'EasyPayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EasyPay-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyPay-tvOS

  target 'EasyPay-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end
