# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyPay' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for EasyPay
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'RNAwesomeCardIO', :path => '../node_modules/react-native-awesome-card-io'

  target 'EasyPayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EasyPay-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyPay-tvOS

  target 'EasyPay-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end